# HUD
HudValueDisplayLg: str = "value_display_large.png"
HudValueDisplayMd: str = "value_display_normal.png"
HudValueDisplaySm: str = "value_display_small.png"
HudValueDisplayXl: str = "value_display_xl.png"

# Icons
IcLogo: str = "logo24x24.png"

IcLogo16: str = "logo16x16.png"
IcLogo24: str = "logo24x24.png"
IcLogo32: str = "logo32x32.png"
IcLogo48: str = "logo48x48.png"
IcLogo256: str = "logo256x256.png"

IcCoins: str = "coins.png"
IcXp: str = "xp.png"

IcTime: str = "time.png"

IcMailOff: str = "mail_0.png"
IcMailOn: str = "mail_1.png"

IcChest: str = "chest.png"

# Icons Satanic Zone Buffs:
IcBuffDefault: str = "sz_buff_default.png"
IcBuff_1: str = "sz_buff_loot.png"
IcBuff_2: str = "sz_buff_loot.png"
IcBuff_3: str = "sz_buff_runes.png"
IcBuff_4: str = "sz_buff_gold.png"
IcBuff_5: str = "sz_buff_heroic.png"
IcBuff_6: str = "sz_buff_angelic.png"
IcBuff_7: str = "sz_buff_zephy.png"
IcBuff_8: str = "sz_buff_fury_of_tempest.png"
IcBuff_9: str = "sz_buff_cast_rate.png"
IcBuff_10: str = "sz_buff_onslaught.png"
IcBuff_11: str = "sz_buff_nether_surge.png"
IcBuff_12: str = "sz_buff_relics.png"
IcBuff_13: str = "sz_buff_goblin.png"
IcBuff_14: str = "sz_buff_mf.png"
IcBuff_15: str = "sz_buff_mf.png"
IcBuff_16: str = "sz_buff_mf.png"
IcBuff_17: str = "sz_buff_combat_training.png"
IcBuff_18: str = "sz_buff_combat_training.png"
IcBuff_19: str = "sz_buff_combat_training.png"  
IcBuff_20: str = "sz_buff_clairvoyance.png"
IcBuff_21: str = "sz_buff_aftermath.png"
IcBuff_22: str = "sz_buff_deep_cuts.png"
IcBuff_23: str = "sz_buff_ancient_pack.png"
IcBuff_24: str = "sz_buff_ancient_pack_2.png"
IcBuff_25: str = "sz_buff_ancient_pack_2.png"

# Icons Satanic Zone DeBuffs
IcDebuffDefault: str = "sz_debuff_default.png"
IcDebuff_1: str = "sz_debuff_dusk_shroud.png"
IcDebuff_2: str = "sz_debuff_elemental_erosion.png"
IcDebuff_3: str = "sz_debuff_sundered_armor.png"
IcDebuff_4: str = "sz_debuff_vitality_drain.png"
IcDebuff_5: str = "sz_debuff_essence_drain.png"
IcDebuff_6: str = "sz_debuff_abyssal_gloom.png"
IcDebuff_7: str = "sz_debuff_skill_debilitation.png"
IcDebuff_8: str = "sz_debuff_weakening_essence.png"
IcDebuff_9: str = "sz_debuff_lifeflow_starvation.png"
IcDebuff_10: str = "sz_debuff_sanguine_impairment.png"
IcDebuff_11: str = "sz_debuff_arcane_impairment.png"
IcDebuff_12: str = "sz_debuff_consumed_time.png"
IcDebuff_13: str = "sz_debuff_absolute_limbo.png"
IcDebuff_14: str = "sz_debuff_boulder_fall.png"
IcDebuff_15: str = "sz_debuff_lingering_evil.png"
IcDebuff_16: str = "sz_debuff_fatal_wounds.png"
IcDebuff_17: str = "sz_debuff_bloated_veins.png"
IcDebuff_18: str = "sz_debuff_abnormal_dwelling.png"
IcDebuff_19: str = "sz_debuff_colossal_bloating.png"
IcDebuff_20: str = "sz_debuff_necrosis.png"
IcDebuff_21: str = "sz_debuff_venomous_presence.png"
IcDebuff_22: str = "sz_debuff_flaming_agony.png"
IcDebuff_23: str = "sz_debuff_unholy_agility.png"
IcDebuff_24: str = "sz_debuff_broken_armor.png"
IcDebuff_25: str = "sz_debuff_hemorrhage.png"
IcDebuff_26: str = "sz_debuff_crippling_slow.png"

# Font Colors
FcDefault: str = "<font color=\"#C3AF75\">"
FcAngelic: str = "<font color=\"#F6F794\">"
FcHeroic: str = "<font color=\"#00FFAE\">"
FcSatanic: str = "<font color=\"#CA1717\">"
FcBlue: str = "<font color=\"#5050AE\">"