# src/consts/satanic_debuffs.py
satanic_debuffs = {
    "Dusk's Shroud": "Light Radius decreased by -20%",
    "Elemental Erosion": "All Resistances decreased by -75%",
    "Sundered Armor": "Damage Taken increased by -25%",
    "Vitality Drain": "Life decreased by -25%",
    "Essence Drain": "Mana decreased by -25%",
    "Abyssal Gloom": "Darkness increased by 100%",
    "Skill Debilitation": "All Skills decreased by -10%",
    "Weakening Essence": "All Attributes decreased by 20%",
    "Lifeflow Starvation": "Life and Mana replenish decreased by",
    "Sanguine Impairment": "Life Steal decreased by -75%",
    "Arcane Impairment": "Mana Steal decreased by -75%",
    "Consumed Time": "Cooldowns Recovery decreased by 25%",
    "Absolute Limbo": "Cooldowns Recovery decreased by 50%",
    "Boulder Fall": "Monsters have a 3% chance to drop a boulder from the sky on death",
    "Lingering Evil": "Movement Speed reduced by 25%",
    "Fatal Wounds": "Monsters gain a 10% chance to inflict 2x damage",
    "Bloated Veins": "Monsters have 70% increased Life",
    "Abnormal Dwelling": "Monsters have 130% increased Life",
    "Colossal Bloating": "Monsters have 200% increased Life",
    "Necrosis": "Your life is drained by 1% every second",
    "Venomous Presence": "Poison Duration is increased by 200%",
    "Flaming Agony": "Monsters unleash a Fire Nova on death dealing 50% of their damage",
    "Unholy Agility": "Monsters gain increased movement and attack speed",
    "Broken Armor": "You are unable to block attacks and projectiles",
    "Hemorrhage": "Monster attacks inflict a 4 second stacking bleed (10% of their damage)",
    "Crippling Slow": "Monster attacks inflict a 50% slow that lasts 2 seconds",
}